git:
  depth: 1
sudo: false
language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
script: yarn build && yarn test
jobs:
  include:
    - stage: maybe-deploy
      if: branch = master AND env(TRAVIS_EVENT_TYPE) = cron
      script:
        - yarn build
        - yarn deploy
        - git push origin master --follow-tags
